#!/bin/bash
# for University_of_Illinois 2021
# Michael Neill Hartman

# store the number of lines in dataset
NUMBER_OF_LINES=$(wc -l dataset | awk '{print $1}')
NUMBER_OF_LINES=$(($NUMBER_OF_LINES))

# generate a modified_dataset with space IFS from dataset
cat dataset | tr ' ' '_' | tr ';' ' ' > modified_dataset

# translate to one token per line
cat modified_dataset | tr ' ' '\n' > token_per_line

# determine number of lines
NUMBER_OF_LINES=$(wc -l token_per_line | awk '{print $1}')
NUMBER_OF_LINES=$(($NUMBER_OF_LINES))

# make a result file
> result

ITERATOR=1
while [[ $ITERATOR -lt $NUMBER_OF_LINES+1 ]]
do
LINE=$(head -$ITERATOR token_per_line | tail -1)
THIS=$(grep -w "${LINE}" token_per_line | wc -l | awk '{print $1}')
[[ `grep -w "${LINE}" result` == "" ]] && {
GREATER_THAN_771=$((`echo ${THIS} | tr ':' ' ' | awk '{print $1}'`))
[[ $GREATER_THAN_771 -gt 771 ]] && echo "`echo ${THIS}`:`echo ${LINE}`" >> result
} ## [[ `echo ${RESULT}| grep "!${THIS}"` == "" ]] && {

echo "$ITERATOR/$NUMBER_OF_LINES"
[[ $(($ITERATOR % 100)) -eq 0 ]] && {
cat result | sort -n | tr '_' ' ' > patterns.txt 
} ## [[ $(($ITERATOR % 100)) -eq 0 ]] && {
ITERATOR=$(($ITERATOR+1))
done ## while [[ $ITERATOR -lt $NUMBER_OF_LINES+1 ]]

cat result | sort -n | tr '_' ' ' > patterns.txt 

# store submission file
[[ -d part_1 ]] || mkdir -p part_1
mv patterns.txt part_1


# run with:  time bash apriori | tee log



echo "
complete; result in: patterns.txt
"
