#!/bin/bash
# for University_of_Illinois 2021
# Michael Neill Hartman

## MAGIC_BOOLS
PART_1=0

[[ $PART_1 -eq 1 ]] && {
# generate a modified_dataset with space IFS from dataset
cat dataset | tr ' ' '_' | tr ';' ' ' > modified_dataset

# translate to one token per line
cat modified_dataset | tr ' ' '\n' > token_per_line

# determine number of lines
NUMBER_OF_LINES=$(wc -l token_per_line | awk '{print $1}')
NUMBER_OF_LINES=$(($NUMBER_OF_LINES))

# make a result file
> result

ITERATOR=1
while [[ $ITERATOR -lt $NUMBER_OF_LINES+1 ]]
do
LINE=$(head -$ITERATOR token_per_line | tail -1)
THIS=$(grep -w "${LINE}" token_per_line | wc -l | awk '{print $1}')
[[ `grep -w "${LINE}" result` == "" ]] && {
GREATER_THAN_771=$((`echo ${THIS} | tr ':' ' ' | awk '{print $1}'`))
[[ $GREATER_THAN_771 -gt 771 ]] && echo "`echo ${THIS}`:`echo ${LINE}`" >> result
} ## [[ `echo ${RESULT}| grep "!${THIS}"` == "" ]] && {

echo "$ITERATOR/$NUMBER_OF_LINES"
[[ $(($ITERATOR % 100)) -eq 0 ]] && {
cat result | sort -n | tr '_' ' ' > patterns.txt 
} ## [[ $(($ITERATOR % 100)) -eq 0 ]] && {
ITERATOR=$(($ITERATOR+1))
done ## while [[ $ITERATOR -lt $NUMBER_OF_LINES+1 ]]

cat result | sort -n | tr '_' ' ' > patterns.txt 

cp patterns.txt part1

# store submission file
[[ -d part_1 ]] || mkdir -p part_1
mv patterns.txt part_1
} ## [[ $PART_1 -eq 1 ]] && {



cat part1 | tr ' ' '_' | tr ':' ' ' | awk '{print $2}' > tokens

cp tokens tokens2

# determine number of lines
NUMBER_OF_LINES=$(wc -l tokens | awk '{print $1}')
NUMBER_OF_LINES=$(($NUMBER_OF_LINES))

> result2



TOKENS=$(cat tokens)
TOKENS2=$(cat tokens2)

for ITEM in ${TOKENS}
do
ITERATOR=2
while [[ $ITERATOR -lt $NUMBER_OF_LINES+1 ]]
do
CURRENT=$(echo ${TOKENS2} | awk -v i=$ITERATOR '{print $i}')
#THIS_PAIR="${ITEM} ${CURRENT}"

echo "${CURRENT}

" 



THIS=$(grep -w "${ITEM}" modified_dataset | grep -w "${CURRENT}" | wc -l | awk '{print $1}')
THIS=$(($THIS*1))
[[ $THIS -gt 0 ]] && {
THIS_PAIR="${ITEM};${CURRENT}"
OTHER_PAIR="${CURRENT};${ITEM}"
[[ `grep -w "${THIS_PAIR}" result2` == "" && `grep -w "${OTHER_PAIR}" result2` == ""  ]] && {
echo "`echo ${THIS}`:`echo ${THIS_PAIR}`" >> result2
} ## [[ `grep -w "${THIS_PAIR}" result2` == "" && `grep -w "${OTHER_PAIR}" result2` == ""  ]] && {

echo "$ITERATOR/$NUMBER_OF_LINES"
cat result2
} ## [[ $THIS -gt 0 ]] && {

ITERATOR=$(($ITERATOR+1))
done ## while [[ $ITERATOR -lt $NUMBER_OF_LINES+1 ]]
done ## for ITEM in ${TOKENS}

cat result2 | sort -n | tr '_' ' ' > patterns.txt 

cp patterns.txt part2

# store submission file
[[ -d part_2 ]] || mkdir -p part_2
mv patterns.txt part_2

# run with:  time bash apriori | tee log

echo "
complete; results in: 
part_1/patterns.txt
part_2/patterns.txt
"
