#!/bin/bash

# process with given part1

TOKENS=$(cat part1 | tr ' ' '_' | tr ':' ' ' | awk '{for (i=2; i<=NF; i++) print $i}' | tr '\n' '!')

MODIFIED=$(cat modified_dataset | tr '\n' '!')

> res
LARGEST=0
ITERATOR=1
while [[ $ITERATOR -lt 77186 ]]
do
LINE=$(head -$ITERATOR modified_dataset | tail -1)
NUMBER_OF_TOKENS_IN_LINE=$(echo ${LINE} | awk '{print NF}')
NUMBER_OF_TOKENS_IN_LINE=$(($NUMBER_OF_TOKENS_IN_LINE*1))
[[ $NUMBER_OF_TOKENS_IN_LINE -gt $LARGEST  ]] && LARGEST=$NUMBER_OF_TOKENS_IN_LINE
ALL_PRESENT=1
while [[ $NUMBER_OF_TOKENS_IN_LINE -gt 0 ]]
do
THIS=$(echo "$LINE" | awk -v i=$NUMBER_OF_TOKENS_IN_LINE '{print $i}')
[[ `echo ${TOKENS} | tr '!' '\n' | grep ${THIS}` == "" ]] && ALL_PRESENT=0
NUMBER_OF_TOKENS_IN_LINE=$(($NUMBER_OF_TOKENS_IN_LINE-1))
done ## while [[ $NUMBER_OF_TOKENS_IN_LINE -gt 0 ]]
[[ $ALL_PRESENT -eq 1 ]] && {
echo "$LINE" >> res
uniq res > result
> res
} ## [[ $ALL_PRESENT -eq 1 ]] && {
ITERATOR=$(($ITERATOR+1))
[[ $(($ITERATOR % 1000)) -eq 0 ]] && {
echo "






$ITERATOR $LARGEST 
`cat res`





"
} ## [[ $(($ITERATOR % 1000)) -eq 0 ]] && {
done ## while $ITERATOR -lt 77186

echo "complete!"
