#!/bin/bash




TOKENS=$(cat part1 | tr ' ' '_' | tr ':' ' ' | awk '{for (i=2; i<=NF; i++) print $i}' | tr '\n' '!')

MODIFIED=$(cat modified_dataset | tr '\n' '!')

> res
IS_MATCH=""
LARGEST=0
ITERATOR=1
while [[ $ITERATOR -lt 77186 ]]
do
LINE=$(head -$ITERATOR modified_dataset | tail -1)
NUMBER_OF_TOKENS_IN_LINE=$(echo ${LINE} | awk '{print NF}')
NUMBER_OF_TOKENS_IN_LINE=$(($NUMBER_OF_TOKENS_IN_LINE*1))
[[ $NUMBER_OF_TOKENS_IN_LINE -gt $LARGEST  ]] && LARGEST=$NUMBER_OF_TOKENS_IN_LINE
#echo "
#$LINE
#$NUMBER_OF_TOKENS_IN_LINE
#$LARGEST
#"

ALL_PRESENT=1
while [[ $NUMBER_OF_TOKENS_IN_LINE -gt 0 ]]
do
THIS=$(echo "$LINE" | awk -v i=$NUMBER_OF_TOKENS_IN_LINE '{print $i}')
[[ `echo ${TOKENS} | tr '!' '\n' | grep ${THIS}` == "" ]] && ALL_PRESENT=0
#CURRENT=$(echo ${TOKENS} | awk -v i=$ITERATOR '{print $i}')
#echo "$LINE" | awk -v i=$NUMBER_OF_TOKENS_IN_LINE '{print $i}' >> res


#[[ ${CURRENT} != ${ITEM} ]] && 



#CURRENT=$(echo ${TOKENS} | awk -v i=$ITERATOR '{print $i}')
#PAIR_2_CURRENT=$(echo ${TOKENS} | awk -v i=$ITERATOR '{print $i}')
#[[ ${CURRENT} != ${ITEM} ]] && 


NUMBER_OF_TOKENS_IN_LINE=$(($NUMBER_OF_TOKENS_IN_LINE-1))
done ## while [[ $NUMBER_OF_TOKENS_IN_LINE -gt 0 ]]
[[ $ALL_PRESENT -eq 1 ]] && echo "$LINE" >> res
ITERATOR=$(($ITERATOR+1))

[[ $(($ITERATOR % 1000)) -eq 0 ]] && echo "$ITERATOR $LARGEST `cat res`"

done ## while $ITERATOR -lt 77186

echo ${LARGEST}

#echo ${LARGEST} > res

exec true
TOKENS=$(cat part1)

for ITEM in ${TOKENS}
do
ITERATOR=1
while [[ $ITERATOR -lt $NUMBER_OF_LINES+1 ]]
do
CURRENT=$(echo ${TOKENS} | awk -v i=$ITERATOR '{print $i}')
NEXT_ITR=1
while [[ $NEXT_ITR -lt $NUMBER_OF_LINES+1 ]]
do
NEXT=$(echo ${TOKENS} | awk -v i=$NEXT_ITR '{print $i}')

THIS=$(grep "${NEXT}" modified_dataset | grep "${CURRENT}" | grep "${ITEM}" | wc -l | awk '{print $1}')
THIS=$(($THIS*1))

echo "
$THIS
"

[[ $THIS -gt 0 ]] && {
THIS_TRIP="${ITEM};${CURRENT};${NEXT}"
[[ `grep "${ITEM}" result2 | grep "${CURRENT}" | grep "${NEXT}"` == "" && ${CURRENT} != ${ITEM} && ${CURRENT} != ${NEXT} && ${NEXT} != ${ITEM} ]] && {
GREATER_THAN_771=$((`echo ${THIS} | tr ':' ' ' | awk '{print $1}'`))
[[ $GREATER_THAN_771 -gt 771 ]] && {
echo "`echo ${THIS}`:`echo ${THIS_TRIP}`" >> result2
} ## [[ $GREATER_THAN_771 -gt 771 ]] && {
} ## [[ `grep -w "${ITEM}" result2 | grep -w "${CURRENT}" | grep -w "${NEXT}"` == "" && ${CURRENT} != ${ITEM} && ${CURRENT} != ${NEXT} && ${NEXT} != ${ITEM} ]] && {

echo "$NEXT_ITR/$NUMBER_OF_LINES"
cat result2
} ## [[ $THIS -gt 0 ]] && {

NEXT_ITR=$(($NEXT_ITR+1))
done ## while [[ $ITERATOR -lt $NUMBER_OF_LINES+1 ]]
ITERATOR=$(($ITERATOR+1))
done ## while [[ $ITERATOR -lt $NUMBER_OF_LINES+1 ]]
done ## for ITEM in ${TOKENS}}
