#!/bin/bash

# process with given part1

TOKENS=$(cat part1 | tr ' ' '_' | tr ':' ' ' | awk '{for (i=2; i<=NF; i++) print $i}' | tr '\n' '!')

MODIFIED=$(cat modified_dataset | tr '\n' '!')

> result
> subs
> res
LARGEST=0
ITERATOR=1
while [[ $ITERATOR -lt 77187 ]] ## +1
do
LINE=$(head -$ITERATOR modified_dataset | tail -1)
NUMBER_OF_TOKENS_IN_LINE=$(echo ${LINE} | awk '{print NF}')
NUMBER_OF_TOKENS_IN_LINE=$(($NUMBER_OF_TOKENS_IN_LINE*1))
[[ $NUMBER_OF_TOKENS_IN_LINE -gt $LARGEST  ]] && LARGEST=$NUMBER_OF_TOKENS_IN_LINE
ALL_PRESENT=1
while [[ $NUMBER_OF_TOKENS_IN_LINE -gt 0 ]]
do
THIS=$(echo "$LINE" | awk -v i=$NUMBER_OF_TOKENS_IN_LINE '{print $i}')
[[ `echo ${TOKENS} | tr '!' '\n' | grep ${THIS}` == "" ]] && ALL_PRESENT=$(($NUMBER_OF_TOKENS_IN_LINE-1))
NUMBER_OF_TOKENS_IN_LINE=$(($NUMBER_OF_TOKENS_IN_LINE-1))
done ## while [[ $NUMBER_OF_TOKENS_IN_LINE -gt 0 ]]
[[ $ALL_PRESENT -gt 1 ]] && {
cat subs > res
echo "$LINE" >> res
cat res > subs
#uniq res > subs
> res
} ## [[ $ALL_PRESENT -gt 1 ]] && {
[[ $ALL_PRESENT -eq 1 ]] && {
cat result > res
echo "$LINE" >> res
cat res > result
#uniq res > result
> res
} ## [[ $ALL_PRESENT -eq 1 ]] && {
ITERATOR=$(($ITERATOR+1))
[[ $(($ITERATOR % 1000)) -eq 0 ]] && {
echo "

`cat result`
`wc -l result`
`wc -l subs`
$ITERATOR $LARGEST 

"
} ## [[ $(($ITERATOR % 1000)) -eq 0 ]] && {
done ## while $ITERATOR -lt 77186

echo "complete!"
