#!/bin/bash

# b_determine_average_usage_delta_from_process

PROCESS_TO_DELTA=$@

RUN_DELTA(){
RUN_LOWEST=$(bash b_determine_lowest_non_0_idle_cpu)

BEFORE=$RUN_LOWEST

#echo "BEFORE: $RUN_LOWEST"

#echo "RUNNING: $PROCESS_TO_DELTA"

($PROCESS_TO_DELTA) > /dev/null
#($PROCESS_TO_DELTA)

#sleep 1

RUN_LOWEST=$(bash b_determine_lowest_non_0_idle_cpu)

AFTER=$RUN_LOWEST

#echo "AFTER: $RUN_LOWEST"

DELTA=$(($BEFORE-$AFTER))

#echo "DELTA: $DELTA"
} ## RUN_DELTA(){

RUN_DELTA
while [[ `echo $DELTA` =~ '-' ]] 
do
RUN_DELTA
done
echo "$DELTA" 

