#!/bin/bash
# for University_of_Illinois 2021
# Michael Neill Hartman

# b_remove_lines_matching_input_string implementation

SOURCE_FILE=patterns.txt
OUTPUT_FILE=patterns.txt
TARGET_DIRECTORY=/Volumes/ramdisk/assignment_2
STRING_TO_REMOVE="100:"
START_AT=1

cd ${TARGET_DIRECTORY}
NUMBER_OF_LINES=$(wc -l ${SOURCE_FILE} | awk '{print $1}')
NUMBER_OF_LINES=$(($NUMBER_OF_LINES+1))
pwd
echo "
START_AT------$START_AT
SOURCE_FILE---$SOURCE_FILE
OUTPUT_FILE---$OUTPUT_FILE
"
> working
# begin processing line at passed value from START_AT
ITERATOR=$START_AT
while [[ $ITERATOR -ne $NUMBER_OF_LINES+1 ]]
do
LINE=$(cat ${SOURCE_FILE} | head -$ITERATOR | tail -1)
CONTAINS_STRING_TO_REMOVE=$(echo "${LINE}" | grep -c "${STRING_TO_REMOVE}")
[[ "${CONTAINS_STRING_TO_REMOVE}" == "0" ]] && {
echo "${LINE}" >> working
} ## [[ "${CONTAINS_STRING_TO_REMOVE}" == "0" ]] && {
echo "
$ITERATOR / $NUMBER_OF_LINES
"
ITERATOR=$(($ITERATOR+1))
done ## while [[ $ITERATOR -ne $NUMBER_OF_LINES+1 ]]
cat working > ${OUTPUT_FILE}
